name: Build and Deploy
on:
  workflow_dispatch:
permissions:
  id-token: write
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 21
          cache: 'maven'
      - name: Java & Maven Version
        run: |
          java -version
          mvn -version
      - name: Build with Maven
        run: |
          mvn clean package
      - name: verify Build Artifact
        run: |
          ls -l target/*.jar
          echo "Build artifact exists: $(ls -l target/*.jar)"
      - name: Prepare EBS package
        run: |
          mkdir -p eb-deployment
          cp target/*.jar eb-deployment/
          echo "web: java -jar *.jar" > eb-deployment/Procfile
          ls -la eb-deployment
      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: streamflix-artifact
          path: eb-deployment
  deployinfrastructure:
    name: Terraform
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ap-south-2
          role-session-name: githublink
      - name: Verify AWS authentication
        run: |
          aws sts get-caller-identity
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
      - name: Terraform Init
        run: |
          cd terraform
          terraform init
      - name: Terraform Plan
        run: |
          cd terraform
          terraform plan
      - name: Terraform Apply
        run: |
          cd terraform
          terraform apply -auto-approve
  deployapplication:
    name: Deploy EBS Application
    runs-on: ubuntu-latest
    needs: deployinfrastructure
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ap-south-2
          role-session-name: githublink
      - name: Verify AWS authentication
        run: |
          aws sts get-caller-identity
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: streamflix-artifact  
          path: deployment
      - name: Verify deloyment fies
        run: |
          ls -la deployment
          echo "Proc file content"
          cat deployment/Procfile
          test -f deployment/*.jar && echo "Jar file exists" || echo "Jar file does not exist"
      - name: create zip file
        run: |
          cd deployment
          zip -r ../streamflix-deployment.zip .
          cd ..
          unzip -l streamflix-deployment.zip
      - name: Deploy to Elastic Beanstalk
        uses: aws-actions/elastic-beanstalk-deploy@v1
        with:
          application-name: Streamflix
          environment-name: streamflix-env
          version-label: streamflix-${{ github.run_number }}
          region: ap-south-2
          deployment-package-path: streamflix-deployment.zip